My Project: src/NetworkManager.cpp File Reference
NetworkManager.cpp File Reference
#include "Camera.hpp"
#include "NetworkManager.hpp"
#include "DeviceManager.hpp"
#include "GlobalSettings.hpp"
#include <rc_genicam_api/system.h>
#include <rc_genicam_api/interface.h>
#include <rc_genicam_api/device.h>
#include <rc_genicam_api/nodemap_out.h>
#include <GenApi/GenApi.h>
#include <iostream>
#include <memory>
#include <string>
#include <stdexcept>
#include <chrono>
#include <thread>
#include <iomanip>
#include <signal.h>
#include <atomic>
#include <set>
#include <fstream>
#include <algorithm>
#include <deque>
#include <random>
#include <filesystem>
#include "qcustomplot.h"
#include <QFile>
#include <QTextStream>
#include <QVector>
#include <QMap>
#include <QStringList>
#include <QDebug>
#include <QDir>
#include <QRegularExpression>
Functions
uint32_t ipToDecimal (std::string ip)
Variables
double fpsUpperBound = getGlobalFpsUpperBound()
double fpsLowerBound = getGlobalFpsLowerBound()
Function Documentation
ipToDecimal()
uint32_t ipToDecimal (std::string ip)
Definition at line 484 of file NetworkManager.cpp.
 {
     std::vector<std::string> octets;
     std::stringstream ss(ip);
     std::string octet;
     while (std::getline(ss, octet, '.'))
     {
         octets.push_back(octet);
     }
     uint32_t decimal = (std::stoi(octets[0]) << 24) + (std::stoi(octets[1]) << 16) + (std::stoi(octets[2]) << 8) + std::stoi(octets[3]);
     return decimal;
 }
Variable Documentation
fpsLowerBound
double fpsLowerBound = getGlobalFpsLowerBound()
Definition at line 38 of file NetworkManager.cpp.
Referenced by NetworkManager::calculateMaxFps().
fpsUpperBound
double fpsUpperBound = getGlobalFpsUpperBound()
Definition at line 37 of file NetworkManager.cpp.
Referenced by NetworkManager::calculateMaxFps(), and NetworkManager::setExposureAndFps().