My Project: DeviceManager Class Reference
DeviceManager Class Reference
Library component of the TU Berlin industrial automation framework.
#include <DeviceManager.hpp>
Public Member Functions
DeviceManager ()
Constructs a DeviceManager instance and initialize cameras lists.
~DeviceManager ()
void getAvailableCameras ()
Discovers available cameras on the network.
void createCameras (std::list< std::string > deviceIds)
Creates Camera objects for the specified device IDs.
const std::set< std::shared_ptr< rcg::Device > > & getAvailableCamerasList () const
Returns the list of available cameras.
std::shared_ptr< rcg::Device > getAvailableCameraByID (const std::string &deviceId)
Returns a device by its ID.
std::shared_ptr< rcg::Device > getAvailableCameraBySN (const std::string &deviceSN)
Returns a device by its serial number.
std::list< std::string > listAvailableCamerasByID ()
Lists all available camera IDs.
const std::list< std::shared_ptr< Camera > > & getOpenCameras () const
Returns the list of currently open cameras.
std::shared_ptr< Camera > getOpenCameraByID (const std::string &deviceId)
Returns an open camera by its ID.
bool listopenCameras ()
Lists the currently open cameras.
void setPixelFormatAll (std::string pixelFormat)
Sets the pixel format for all open cameras.
void setExposureTimeAll (double exposureTime)
Sets the exposure time for all open cameras.
void setGainAll (float gain)
Sets the gain value for all open cameras.
void setHeightAll (int height)
Sets the height for all open cameras.
void setWidthAll (int width)
Sets the width for all open cameras.
Public Attributes
uint32_t groupKey = 1
Group key for multi-camera synchronization.
uint32_t groupMask = 0x00000001
Group mask for multi-camera synchronization.
Private Member Functions
bool createCamera (const std::string &deviceId)
Creates a camera by device ID.
bool closeCamera (const std::string &deviceId)
Closes a camera by device ID.
void enumerateDevicesFromDefault (const std::vector< std::shared_ptr< rcg::System >> &systems)
Enumerates devices from default systems.
void enumerateDevicesFromSystems (const std::vector< std::shared_ptr< rcg::System >> &systems)
Enumerates devices from given systems.
bool listCamera (std::shared_ptr< Camera > camera)
Lists a single camera.
Private Attributes
std::list< std::shared_ptr< Camera > > openCamerasList
List of currently open cameras.
std::set< std::shared_ptr< rcg::Device > > availableCamerasList
Set of available cameras.
Detailed Description
Library component of the TU Berlin industrial automation framework.
Copyright (c) 2025 TU Berlin, Institut für Werkzeugmaschinen und Fabrikbetrieb Fachgebiet Industrielle Automatisierungstechnik Author: Yessmine Chabchoub All rights reserved.
Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
Neither the name of the copyright holder nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission.
Note
DISCLAIMER THIS SOFTWARE IS PROVIDED "AS IS" WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED. IN NO EVENT SHALL THE COPYRIGHT HOLDER BE LIABLE FOR ANY DAMAGES ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE.
DeviceManager class handles camera discovery, initialization, and configuration.
Definition at line 44 of file DeviceManager.hpp.
Constructor & Destructor Documentation
DeviceManager()
DeviceManager::DeviceManager ()
Constructs a DeviceManager instance and initialize cameras lists.
Library component of the TU Berlin industrial automation framework.
Copyright (c) 2025 TU Berlin, Institut für Werkzeugmaschinen und Fabrikbetrieb Fachgebiet Industrielle Automatisierungstechnik Author: Yessmine Chabchoub All rights reserved.
Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
Neither the name of the copyright holder nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission.
Note
DISCLAIMER THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
Definition at line 47 of file DeviceManager.cpp.
 {
     availableCamerasList = {};
     openCamerasList = {};
 }
References availableCamerasList, and openCamerasList.
~DeviceManager()
DeviceManager::~DeviceManager ()
Definition at line 53 of file DeviceManager.cpp.
 {
     availableCamerasList = {};
     for (auto &camera : openCamerasList)
     {
         closeCamera(camera->deviceInfos.id);
     }
 }
References availableCamerasList, closeCamera(), and openCamerasList.
Member Function Documentation
closeCamera()
bool DeviceManager::closeCamera (const std::string & deviceId) private
Closes a camera by device ID.
Definition at line 280 of file DeviceManager.cpp.
 {
     try
     {
         std::shared_ptr<Camera> camera = getOpenCameraByID(deviceId);
         camera->~Camera();
         openCamerasList.remove(camera);
         return true;
     }
     catch (const std::exception &ex)
     {
         std::cerr << RED << "Failed to remove camera: " << ex.what() << RESET << std::endl;
         return false;
     }
 }
References getOpenCameraByID(), openCamerasList, RED, and RESET.
Referenced by ~DeviceManager().
createCamera()
bool DeviceManager::createCamera (const std::string & deviceId) private
Creates a camera by device ID.
Definition at line 254 of file DeviceManager.cpp.
 {
     try
     {
         std::shared_ptr<rcg::Device> device = getAvailableCameraByID(deviceId);
         if (!device)
         {
             std::cerr << RED << "Failed to create camera: " << deviceId << RESET << std::endl;
             return false;
         }
         std::shared_ptr<Camera> newCamera = std::make_shared<Camera>(device);
         openCamerasList.push_back(newCamera);
         if (debug)
         {
             std::cout << GREEN << "[DEBUG] Camera " << deviceId << ": Added to open Cameras successfully" << RESET << std::endl;
         }
         return true;
     }
     catch (const std::exception &ex)
     {
         std::cerr << RED << "Failed to add camera: " << ex.what() << RESET << std::endl;
         return false;
     }
 }
References debug, getAvailableCameraByID(), GREEN, openCamerasList, RED, and RESET.
Referenced by createCameras().
createCameras()
void DeviceManager::createCameras (std::list< std::string > deviceIds)
Creates Camera objects for the specified device IDs.
Definition at line 116 of file DeviceManager.cpp.
 {
     for (const auto &deviceId : deviceIds)
     {
         createCamera(deviceId);
     }
     return;
 }
References createCamera().
Referenced by SystemManager::enumerateOpenCameras(), SystemManager::ptpDisable(), SystemManager::ptpEnable(), SystemManager::setFeature(), and SystemManager::syncFreeRunStream().
enumerateDevicesFromDefault()
void DeviceManager::enumerateDevicesFromDefault (const std::vector< std::shared_ptr< rcg::System >> & systems) private
Enumerates devices from default systems.
Definition at line 348 of file DeviceManager.cpp.
 {
     for (auto &system : systems)
     {
         try
         {
             system->open();
             std::vector<std::shared_ptr<rcg::Interface>> interfaces = system->getInterfaces();
             if (interfaces.empty())
             {
                 system->close();
                 continue;
             }
             for (auto &interf : interfaces)
             {
                 try
                 {
                     interf->open();
                     std::vector<std::shared_ptr<rcg::Device>> devices = interf->getDevices();
                     for (auto &device : devices)
                     {
                         // Only process valid devices that match the vendor
                         // Check if we already have this device ID
                         if (!getAvailableCameraBySN(device->getSerialNumber()))
{
                             availableCamerasList.insert(device);
                         }
                     }
                     interf->close();
                 }
                 catch (const std::exception &ex)
                 {
                     std::cerr << RED << "Failed to process interface: " << ex.what() << RESET << std::endl;
                 }
             }
             system->close();
         }
         catch (const std::exception &ex)
         {
             std::cerr << RED << "Failed to open system: " << ex.what() << RESET << std::endl;
         }
     }
 }
References availableCamerasList, getAvailableCameraBySN(), RED, and RESET.
Referenced by getAvailableCameras().
enumerateDevicesFromSystems()
void DeviceManager::enumerateDevicesFromSystems (const std::vector< std::shared_ptr< rcg::System >> & systems) private
Enumerates devices from given systems.
Definition at line 296 of file DeviceManager.cpp.
 {
     for (auto &system : systems)
     {
         try
         {
             system->open();
             std::vector<std::shared_ptr<rcg::Interface>> interfaces = system->getInterfaces();
             if (interfaces.empty())
             {
                 system->close();
                 continue;
             }
             for (auto &interf : interfaces)
             {
                 try
                 {
                     interf->open();
                     std::vector<std::shared_ptr<rcg::Device>> devices = interf->getDevices();
                     for (auto &device : devices)
                     {
                         // Only process valid devices that match the vendor
                         if (device && device->getVendor() == system->getVendor())
{
                             // Check if we already have this device ID
                             if (!getAvailableCameraByID(device->getID()))
{
                                 availableCamerasList.insert(device);
                             }
                         }
                     }
                     interf->close();
                 }
                 catch (const std::exception &ex)
                 {
                     std::cerr << RED << "Failed to process interface: " << ex.what() << RESET << std::endl;
                 }
             }
             system->close();
         }
         catch (const std::exception &ex)
         {
             std::cerr << RED << "Failed to open system: " << ex.what() << RESET << std::endl;
         }
     }
 }
References availableCamerasList, getAvailableCameraByID(), RED, and RESET.
Referenced by getAvailableCameras().
getAvailableCameraByID()
std::shared_ptr< rcg::Device > DeviceManager::getAvailableCameraByID (const std::string & deviceId)
Returns a device by its ID.
Definition at line 130 of file DeviceManager.cpp.
 {
     for (const auto &device : availableCamerasList)
     {
         if (device->getID() == deviceId)
         {
             return device;
         }
     }
     return nullptr;
 }
References availableCamerasList.
Referenced by createCamera(), and enumerateDevicesFromSystems().
getAvailableCameraBySN()
std::shared_ptr< rcg::Device > DeviceManager::getAvailableCameraBySN (const std::string & deviceSN)
Returns a device by its serial number.
Definition at line 142 of file DeviceManager.cpp.
 {
     for (const auto &device : availableCamerasList)
     {
         if (device->getSerialNumber() == deviceSN)
         {
             return device;
         }
     }
     return nullptr;
 }
References availableCamerasList.
Referenced by enumerateDevicesFromDefault().
getAvailableCameras()
void DeviceManager::getAvailableCameras ()
Discovers available cameras on the network.
Definition at line 62 of file DeviceManager.cpp.
 {
     // Clear existing available cameras
     availableCamerasList.clear();
     // First try with system-provided paths
     std::vector<std::shared_ptr<rcg::System>> systems;
     try
     {
         systems = rcg::System::getSystems();
     }
     catch (const std::exception &ex)
     {
         std::cerr << RED << "Failed to get systems: " << ex.what() << RESET << std::endl;
         return;
     }
     if (!systems.empty())
     {
         enumerateDevicesFromSystems(systems);
     }
     else
     {
         std::cerr << RED << "No systems found from default paths." << RESET << std::endl;
     }
     // Then try with the custom path
     try
     {
         if (!defaultCti.empty())
         {
             rcg::System::setSystemsPath(defaultCti.c_str(), nullptr);
             std::vector<std::shared_ptr<rcg::System>> defaultSystems = rcg::System::getSystems();
             if (!defaultSystems.empty())
             {
                 enumerateDevicesFromDefault(defaultSystems);
             }
             else
             {
                 std::cerr << RED << "No systems found from custom path." << RESET << std::endl;
             }
         }
         else
         {
             std::cerr << RED << "Custom CTI path is empty." << RESET << std::endl;
         }
     }
     catch (const std::exception &ex)
     {
         std::cerr << RED << "Error enumerating with custom path: " << ex.what() << RESET << std::endl;
     }
     return;
 }
References availableCamerasList, defaultCti, enumerateDevicesFromDefault(), enumerateDevicesFromSystems(), RED, and RESET.
Referenced by SystemManager::enumerateCameras().
getAvailableCamerasList()
const std::set< std::shared_ptr< rcg::Device > > & DeviceManager::getAvailableCamerasList () const
Returns the list of available cameras.
Definition at line 125 of file DeviceManager.cpp.
 {
     return availableCamerasList;
 }
References availableCamerasList.
getOpenCameraByID()
std::shared_ptr< Camera > DeviceManager::getOpenCameraByID (const std::string & deviceId)
Returns an open camera by its ID.
Definition at line 184 of file DeviceManager.cpp.
 {
     for (const auto &camera : openCamerasList)
     {
         DeviceInfos deviceInfos = camera->deviceInfos;
         if (deviceInfos.id == deviceId)
         {
             return camera;
         }
     }
     return nullptr;
 }
References DeviceInfos::id, and openCamerasList.
Referenced by closeCamera(), and SystemManager::setFeature().
getOpenCameras()
const std::list< std::shared_ptr< Camera > > & DeviceManager::getOpenCameras () const
Returns the list of currently open cameras.
Definition at line 179 of file DeviceManager.cpp.
 {
     return openCamerasList;
 }
References openCamerasList.
Referenced by SystemManager::ptpDisable(), SystemManager::ptpEnable(), and SystemManager::syncFreeRunStream().
listAvailableCamerasByID()
std::list< std::string > DeviceManager::listAvailableCamerasByID ()
Lists all available camera IDs.
Definition at line 153 of file DeviceManager.cpp.
 {
     try
     {
         std::list<std::string> availableCamerasIds;
         for (const std::shared_ptr<rcg::Device> &device : availableCamerasList)
         {
             availableCamerasIds.push_back(device->getID());
         }
         std::cout << "  Available Devices IDs:  ";
         std::cout << std::endl;
         for (const auto &id : availableCamerasIds)
         {
             std::cout << "        Device:             " << id << std::endl;
             std::cout << std::endl;
         }
         std::cout << std::endl;
         return availableCamerasIds;
     }
     catch (const std::exception &ex)
     {
         std::cerr << RED << "Failed to list devices: " << ex.what() << RESET << std::endl;
         return {};
     }
 }
References availableCamerasList, RED, and RESET.
Referenced by SystemManager::enumerateCameras().
listCamera()
bool DeviceManager::listCamera (std::shared_ptr< Camera > camera) private
Lists a single camera.
Definition at line 398 of file DeviceManager.cpp.
 {
     try
     {
         DeviceInfos config = camera->deviceInfos;
         std::cout << "       Device:             " << config.id << std::endl;
         std::cout << "        Vendor:            " << config.vendor << std::endl;
         std::cout << "        Model:             " << config.model << std::endl;
         std::cout << "        TL type:           " << config.tlType << std::endl;
         std::cout << "        Display name:      " << config.displayName << std::endl;
         std::cout << "        Access status:     " << config.accessStatus << std::endl;
         std::cout << "        Serial number:     " << config.serialNumber << std::endl;
         std::cout << "        Current IP:        " << config.currentIP << std::endl;
         std::cout << "        MAC:               " << config.MAC << std::endl;
         std::cout << "        Deprecated FW:     " << (config.deprecatedFW ? "Yes" : "No") << std::endl;
         std::cout << std::endl;
         return true;
     }
     catch (const std::exception &ex)
     {
         std::cerr << RED << "Failed to list devices: " << ex.what() << RESET << std::endl;
         return false;
     }
 }
References DeviceInfos::accessStatus, DeviceInfos::currentIP, DeviceInfos::deprecatedFW, DeviceInfos::displayName, DeviceInfos::id, DeviceInfos::MAC, DeviceInfos::model, RED, RESET, DeviceInfos::serialNumber, DeviceInfos::tlType, and DeviceInfos::vendor.
Referenced by listopenCameras().
listopenCameras()
bool DeviceManager::listopenCameras ()
Lists the currently open cameras.
Definition at line 197 of file DeviceManager.cpp.
 {
     try
     {
         for (const auto &camera : openCamerasList)
         {
             listCamera(camera);
         }
         return true;
     }
     catch (const std::exception &ex)
     {
         std::cerr << RED << "Failed to list devices: " << ex.what() << RESET << std::endl;
         return false;
     }
 }
References listCamera(), openCamerasList, RED, and RESET.
Referenced by SystemManager::enumerateOpenCameras().
setExposureTimeAll()
void DeviceManager::setExposureTimeAll (double exposureTime)
Sets the exposure time for all open cameras.
Definition at line 222 of file DeviceManager.cpp.
 {
     for (const auto &camera : openCamerasList)
     {
         camera->setExposureTime(exposureTime);
     }
 }
References openCamerasList.
Referenced by SystemManager::setFeature().
setGainAll()
void DeviceManager::setGainAll (float gain)
Sets the gain value for all open cameras.
Definition at line 230 of file DeviceManager.cpp.
 {
     for (const auto &camera : openCamerasList)
     {
         camera->setGain(gain);
     }
 }
References openCamerasList.
setHeightAll()
void DeviceManager::setHeightAll (int height)
Sets the height for all open cameras.
Definition at line 238 of file DeviceManager.cpp.
 {
     for (const auto &camera : openCamerasList)
     {
         camera->setHeight(height);
     }
 }
References openCamerasList.
setPixelFormatAll()
void DeviceManager::setPixelFormatAll (std::string pixelFormat)
Sets the pixel format for all open cameras.
Definition at line 214 of file DeviceManager.cpp.
 {
     for (const auto &camera : openCamerasList)
     {
         camera->setPixelFormat(pixelFormat);
     }
 }
References openCamerasList.
Referenced by SystemManager::setFeature().
setWidthAll()
void DeviceManager::setWidthAll (int width)
Sets the width for all open cameras.
Definition at line 246 of file DeviceManager.cpp.
 {
     for (const auto &camera : openCamerasList)
     {
         camera->setWidth(width);
     }
 }
References openCamerasList.
Member Data Documentation
availableCamerasList
std::set<std::shared_ptr<rcg::Device> > DeviceManager::availableCamerasList private
Set of available cameras.
Definition at line 167 of file DeviceManager.hpp.
Referenced by DeviceManager(), enumerateDevicesFromDefault(), enumerateDevicesFromSystems(), getAvailableCameraByID(), getAvailableCameraBySN(), getAvailableCameras(), getAvailableCamerasList(), listAvailableCamerasByID(), and ~DeviceManager().
groupKey
uint32_t DeviceManager::groupKey = 1
Group key for multi-camera synchronization.
Definition at line 126 of file DeviceManager.hpp.
groupMask
uint32_t DeviceManager::groupMask = 0x00000001
Group mask for multi-camera synchronization.
Definition at line 131 of file DeviceManager.hpp.
openCamerasList
std::list<std::shared_ptr<Camera> > DeviceManager::openCamerasList private
List of currently open cameras.
Definition at line 162 of file DeviceManager.hpp.
Referenced by closeCamera(), createCamera(), DeviceManager(), getOpenCameraByID(), getOpenCameras(), listopenCameras(), setExposureTimeAll(), setGainAll(), setHeightAll(), setPixelFormatAll(), setWidthAll(), and ~DeviceManager().
The documentation for this class was generated from the following files:
src/DeviceManager.hpp
src/DeviceManager.cpp