My Project: SystemManager Class Reference
SystemManager Class Reference
Library component of the TU Berlin industrial automation framework.
#include <SystemManager.hpp>
Public Member Functions
SystemManager ()
~SystemManager ()
void enumerateCameras ()
void enumerateOpenCameras (std::list< std::string > camerasIDs)
bool setFeature (std::string featureName, std::string value, std::list< std::string > cameraIDs={})
void syncFreeRunStream (std::list< std::string > camerasIDs, bool saveStream, std::chrono::milliseconds acquisitionDelay)
bool ptpEnable (std::list< std::string > camerasIDs)
bool ptpDisable (std::list< std::string > camerasIDs)
Public Attributes
std::atomic< bool > stopStream {false}
DeviceManager deviceManager
NetworkManager networkManager
StreamManager streamManager
std::list< std::string > availableCamerasIds
Detailed Description
Library component of the TU Berlin industrial automation framework.
Copyright (c) 2025 TU Berlin, Institut für Werkzeugmaschinen und Fabrikbetrieb Fachgebiet Industrielle Automatisierungstechnik Author: Yessmine Chabchoub All rights reserved.
Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
Neither the name of the copyright holder nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission.
Note
DISCLAIMER THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
SystemManager class is the interface for the overall management of the system and its components. It provides methods to initialize the system, enumerate cameras, set features, and manage streaming and PTP.
Definition at line 46 of file SystemManager.hpp.
Constructor & Destructor Documentation
SystemManager()
SystemManager::SystemManager ()
Constructs a systemManager class by initializing all connected GenTl devices.
Definition at line 60 of file SystemManager.cpp.
 {
     try
     {
         std::signal(SIGINT, handleSignal);
         enumerateCameras();
     }
     catch (const std::exception &e)
     {
         std::cerr << "Error during system initialization: " << e.what() << std::endl;
         throw;
     }
 }
References enumerateCameras(), and handleSignal().
~SystemManager()
SystemManager::~SystemManager ()
Definition at line 74 of file SystemManager.cpp.
 {
     try
     {
         rcg::System::clearSystems();
     }
     catch (const std::exception &e)
     {
         std::cerr << "Error during system shutdown: " << e.what() << std::endl;
     }
 }
Member Function Documentation
enumerateCameras()
void SystemManager::enumerateCameras ()
Enumerates all connected cameras and stores their IDs in availableCamerasIds.
Definition at line 86 of file SystemManager.cpp.
 {
     try
     {
         deviceManager.getAvailableCameras();
         availableCamerasIds = deviceManager.listAvailableCamerasByID();
         if (availableCamerasIds.empty())
         {
             throw std::runtime_error("No cameras found. Please check the connections.");
         }
     }
     catch (const std::exception &e)
     {
         std::cerr << "Error during device enumeration: " << e.what() << std::endl;
         throw;
     }
 }
References availableCamerasIds, deviceManager, DeviceManager::getAvailableCameras(), and DeviceManager::listAvailableCamerasByID().
Referenced by SystemManager().
enumerateOpenCameras()
void SystemManager::enumerateOpenCameras (std::list< std::string > camerasIDs)
Enumerates open cameras and lists their IDs.
Parameters
cameraIDs List of camera IDs to enumerate.
Definition at line 105 of file SystemManager.cpp.
 {
     try
     {
         deviceManager.createCameras(camerasIDs);
         deviceManager.listopenCameras();
     }
     catch (const std::exception &e)
     {
         std::cerr << "Error listing available cameras: " << e.what() << std::endl;
         throw;
     }
 }
References DeviceManager::createCameras(), deviceManager, and DeviceManager::listopenCameras().
Referenced by main().
ptpDisable()
bool SystemManager::ptpDisable (std::list< std::string > camerasIDs)
Disables PTP synchronization for the specified cameras.
Parameters
camerasIDs List of camera IDs to disable PTP for.
Returns
true if PTP was disabled successfully, false otherwise.
Definition at line 244 of file SystemManager.cpp.
 {
     try
     {
         deviceManager.createCameras(camerasIDs);
         std::list<std::shared_ptr<Camera>> openCamerasList = deviceManager.getOpenCameras();
         networkManager.disablePtp(openCamerasList);
     }
     catch (const std::exception &e)
     {
         std::cerr << "Error during PTP disable: " << e.what() << std::endl;
         return false;
     }
     return true;
 }
References DeviceManager::createCameras(), deviceManager, NetworkManager::disablePtp(), DeviceManager::getOpenCameras(), and networkManager.
Referenced by main().
ptpEnable()
bool SystemManager::ptpEnable (std::list< std::string > camerasIDs)
Enables PTP synchronization for the specified cameras.
Parameters
camerasIDs List of camera IDs to enable PTP for.
Returns
true if PTP was enabled successfully, false otherwise.
Definition at line 219 of file SystemManager.cpp.
 {
     try
     {
         deviceManager.createCameras(camerasIDs);
         std::list<std::shared_ptr<Camera>> openCamerasList = deviceManager.getOpenCameras();
         if (openCamerasList.empty())
         {
             throw std::runtime_error("No cameras were successfully opened. Please check the camera IDs and connections.");
         }
         if (openCamerasList.size() > 1)
         {
             networkManager.configurePtpSyncFreeRun(openCamerasList);
         }
     }
     catch (const std::exception &e)
     {
         std::cerr << "Error during PTP enable: " << e.what() << std::endl;
         return false;
     }
     return true;
 }
References NetworkManager::configurePtpSyncFreeRun(), DeviceManager::createCameras(), deviceManager, DeviceManager::getOpenCameras(), and networkManager.
Referenced by main().
setFeature()
bool SystemManager::setFeature (std::string featureName, std::string value, std::list< std::string > cameraIDs = {})
Sets a feature for a specific camera or all cameras if no cameraID is provided.
Parameters
featureName Name of the feature to set (e.g., "width", "height", "gain", "exposure_time", "pixel_format").
value Value to set for the feature.
cameraID ID of the camera to set the feature for. If empty, sets the feature for all cameras.
Returns
true if the feature was set successfully, false otherwise.
Definition at line 118 of file SystemManager.cpp.
 {
     try
     {
         if (value.empty())
         {
             throw std::invalid_argument("Value cannot be empty");
         }
         if (!cameraIDs.empty())
         {
             deviceManager.createCameras(cameraIDs);
         }
         for (const auto &cameraID : cameraIDs)
         {
             std::shared_ptr<Camera> camera = deviceManager.getOpenCameraByID(cameraID);
             if (!camera)
             {
                 std::cerr << "Camera ID not found in open cameras: " << cameraID << std::endl;
                 throw std::runtime_error("Camera ID not found in open cameras.");
             }
             if (featureName == "pixel_format")
             {
                 camera->setPixelFormat(value);
             }
             else if (featureName == "exposure_time")
             {
                 camera->setExposureTime(std::stod(value));
             }
             else if (featureName == "gain")
             {
                 camera->setGain(std::stof(value));
             }
             else if (featureName == "width")
             {
                 camera->setWidth(std::stoi(value));
             }
             else if (featureName == "height")
             {
                 camera->setHeight(std::stoi(value));
             }
             else
             {
                 throw std::invalid_argument("Invalid feature name: " + featureName);
             }
         }
         if (cameraIDs.empty())
         {
             if (featureName == "pixel_format")
             {
                 deviceManager.setPixelFormatAll(value);
             }
             else if (featureName == "exposure_time")
             {
                 deviceManager.setExposureTimeAll(std::stod(value));
             }
             else
             {
                 throw std::invalid_argument("Camera ID is required for setting feature: " + featureName);
             }
         }
         return true;
     }
     catch (const std::exception &e)
     {
         std::cerr << "Error setting feature: " << e.what() << std::endl;
         return false;
     }
 }
References DeviceManager::createCameras(), deviceManager, DeviceManager::getOpenCameraByID(), DeviceManager::setExposureTimeAll(), and DeviceManager::setPixelFormatAll().
Referenced by main().
syncFreeRunStream()
void SystemManager::syncFreeRunStream (std::list< std::string > camerasIDs, bool saveStream, std::chrono::milliseconds acquisitionDelay)
Starts synchronized streaming for the specified cameras.
Parameters
camerasIDs List of camera IDs to start streaming for.
saveStream Flag indicating whether to save the stream.
acquisitionDelay Delay in milliseconds before starting the acquisition.
Definition at line 192 of file SystemManager.cpp.
 {
     try
     {
         std::list<std::shared_ptr<Camera>> openCamerasList = deviceManager.getOpenCameras();
         if (openCamerasList.empty())
         {
             deviceManager.createCameras(camerasIDs);
             openCamerasList = deviceManager.getOpenCameras();
         }
         if (openCamerasList.size() > 1)
         {
             networkManager.configurePtpSyncFreeRun(openCamerasList);
         }
         streamManager.startPtpSyncFreeRun(openCamerasList, stopStream, saveStream, acquisitionDelay);
     }
     catch (const std::exception &e)
     {
         std::cerr << "Error during syncFreeRunStream: " << e.what() << std::endl;
         throw;
     }
 }
References NetworkManager::configurePtpSyncFreeRun(), DeviceManager::createCameras(), deviceManager, DeviceManager::getOpenCameras(), networkManager, StreamManager::startPtpSyncFreeRun(), stopStream, and streamManager.
Referenced by main().
Member Data Documentation
availableCamerasIds
std::list<std::string> SystemManager::availableCamerasIds
Definition at line 99 of file SystemManager.hpp.
Referenced by enumerateCameras().
deviceManager
DeviceManager SystemManager::deviceManager
Definition at line 96 of file SystemManager.hpp.
Referenced by enumerateCameras(), enumerateOpenCameras(), ptpDisable(), ptpEnable(), setFeature(), and syncFreeRunStream().
networkManager
NetworkManager SystemManager::networkManager
Definition at line 97 of file SystemManager.hpp.
Referenced by ptpDisable(), ptpEnable(), and syncFreeRunStream().
stopStream
std::atomic<bool> SystemManager::stopStream {false}
Definition at line 95 of file SystemManager.hpp.
Referenced by syncFreeRunStream().
streamManager
StreamManager SystemManager::streamManager
Definition at line 98 of file SystemManager.hpp.
Referenced by syncFreeRunStream().
The documentation for this class was generated from the following files:
src/SystemManager.hpp
src/SystemManager.cpp