My Project: Camera Class Reference
Camera Class Reference
#include <Camera.hpp>
Public Member Functions
Camera (std::shared_ptr< rcg::Device > device, CameraConfig cameraConfig={}, StreamConfig streamConfig={}, NetworkConfig networkConfig={})
~Camera ()
void startStreaming (std::atomic< bool > &stopStream, std::mutex &globalFrameMutex, std::vector< cv::Mat > &globalFrames, int index, bool saveStream)
void stopStreaming (std::shared_ptr< rcg::Stream > stream)
void setPtpConfig (bool enable=true)
void setFreeRunMode ()
void setScheduledActionCommand (uint32_t actionDeviceKey, uint32_t groupKey, uint32_t groupMask)
void setPacketSizeB (double size)
void setBandwidthDelays (const std::shared_ptr< Camera > &camera, double camIndex, double numCams, double packetSizeB, double linkSpeedBps, double bufferPercent)
void setFps (double fpsUpperBound)
void setGain (float gain)
void setHeight (int height)
void setWidth (int width)
void setExposureTime (double exposureTime)
void setPixelFormat (std::string pixelFormat)
void issueScheduledActionCommand (uint32_t actionDeviceKey, uint32_t groupKey, uint32_t groupMask, int64_t delayS, const std::string &targetIP="255.255.255.255")
double calculateFps (double linkSpeedBps, double packetSizeB)
double getExposureTime ()
double getFps ()
std::string getCurrentIP ()
std::string getMAC ()
void getPtpConfig ()
void getTimestamps ()
double getLastSavedFps () const
Public Attributes
DeviceInfos deviceInfos
CameraConfig cameraConfig
PtpConfig ptpConfig
NetworkConfig networkConfig
StreamConfig streamConfig
std::shared_ptr< GenApi::CNodeMapRef > nodemap
Private Member Functions
void processRawFrame (const cv::Mat &rawFrame, cv::Mat &outputFrame, uint64_t pixelFormat)
Process a raw frame based on the pixel format.
void updateGlobalFrame (std::mutex &globalFrameMutex, std::vector< cv::Mat > &globalFrames, int index, cv::Mat &frame, int &frameCount, std::chrono::steady_clock::time_point &lastTime)
void processFrame (const rcg::Buffer *buffer, cv::Mat &outputFrame)
void cleanupStream (std::shared_ptr< rcg::Stream > &stream)
std::shared_ptr< rcg::Stream > initializeStream ()
void initializeVideoWriter (int width, int height)
void saveFrameToVideo (cv::VideoWriter &videoWriter, const cv::Mat &frame)
void saveFrameToPng (const cv::Mat &frame)
double calculatePacketDelayNs (double packetSizeB, double linkSpeedBps, double bufferPercent, double numCams)
double calculateFrameTransmissionCycle (double linkSpeedBps, double packetSizeB)
double calculateRawFrameSizeB (int width, int height, PfncFormat_ pixelFormat)
bool isFpsStableForSaving (double tolerance=1.0) const
void adjustFpsDynamically (double fps, double &lastFpsAdjustment)
bool isDottedIP (const std::string &ip)
std::string decimalToIP (uint32_t decimalIP)
std::string hexToIP (const std::string &hexIP)
std::string decimalToMAC (uint64_t decimalMAC)
std::string hexToMAC (const std::string &hexMAC)
PfncFormat_ getPixelFormat (const std::string &format)
int getBitsPerPixel (PfncFormat_ pixelFormat)
void logBandwidthDelaysToCSV (const std::string &camID, int64_t packetDelayNs, int64_t transmissionDelayNs)
Private Attributes
std::shared_ptr< rcg::Device > device
unsigned long frameCounter = 0
double lastSavedFps = 0.0
cv::VideoWriter videoWriter
Detailed Description
Definition at line 69 of file Camera.hpp.
Constructor & Destructor Documentation
Camera()
Camera::Camera (std::shared_ptr< rcg::Device > device, CameraConfig cameraConfig = {}, StreamConfig streamConfig = {}, NetworkConfig networkConfig = {})
Definition at line 37 of file Camera.cpp.
     : device(device), cameraConfig(cameraConfig), streamConfig(streamConfig), networkConfig(networkConfig)
 {
     if (device)
     {
         this->device = device;
         try
         {
             device->open(rcg::Device::CONTROL);
             if (debug)
                 std::cout << GREEN << "[DEBUG] Camera " << device->getID() << ": Opened successfully" << RESET << std::endl;
         }
         catch (const std::exception &ex)
         {
             std::cerr << RED << "Error: Failed to open camera " << device->getID() << ": " << ex.what() << RESET << std::endl;
             std::exit(EXIT_FAILURE);
         }
         this->nodemap = device->getRemoteNodeMap();
         // Assign device info
         deviceInfos.id = device->getID();
         deviceInfos.vendor = device->getVendor();
         deviceInfos.model = device->getModel();
         deviceInfos.tlType = device->getTLType();
         deviceInfos.displayName = device->getDisplayName();
         deviceInfos.accessStatus = device->getAccessStatus();
         deviceInfos.serialNumber = device->getSerialNumber();
         deviceInfos.version = device->getVersion();
         deviceInfos.timestampFrequency = device->getTimestampFrequency();
         deviceInfos.currentIP = getCurrentIP();
         deviceInfos.MAC = getMAC();
         deviceInfos.deprecatedFW = rcg::getString(nodemap, "PtpEnable").empty(); // ToDo
         // Populate CameraConfig struct
         if (cameraConfig.exposure > 0 || cameraConfig.gain > 0 || cameraConfig.width > 0 || cameraConfig.height > 0)
         {
             this->cameraConfig = cameraConfig; // Use provided values
         }
         else
         {
             // Read from camera if not provided
             if (deviceInfos.deprecatedFW)
             {
                 this->cameraConfig.exposure = rcg::getInteger(nodemap, "ExposureTimeAbs");
             }
             else
             {
                 this->cameraConfig.exposure = rcg::getInteger(nodemap, "ExposureTime");
             }
             this->cameraConfig.gain = rcg::getFloat(nodemap, "Gain");
             this->cameraConfig.width = rcg::getInteger(nodemap, "Width");
             this->cameraConfig.height = rcg::getInteger(nodemap, "Height");
             std::string formatString = rcg::getEnum(nodemap, "PixelFormat");
             this->cameraConfig.pixelFormat = getPixelFormat(formatString);
         }
         // Populate NetworkConfig struct
         if (networkConfig.deviceLinkSpeedBps > 0 || networkConfig.packetDelayNs > 0 || networkConfig.transmissionDelayNs > 0)
         {
             this->networkConfig = networkConfig; // Use provided values
         }
         // Populate StreamConfig struct
         if (streamConfig.videoWidth > 0 || streamConfig.videoHeight > 0)
         {
             this->streamConfig = streamConfig; // Use provided values
         }
             }
     else
     {
         std::cerr << "Error: No valid device provided.\n";
     }
 }
References DeviceInfos::accessStatus, cameraConfig, DeviceInfos::currentIP, debug, DeviceInfos::deprecatedFW, device, deviceInfos, NetworkConfig::deviceLinkSpeedBps, DeviceInfos::displayName, CameraConfig::exposure, CameraConfig::gain, getCurrentIP(), getMAC(), getPixelFormat(), GREEN, CameraConfig::height, DeviceInfos::id, DeviceInfos::MAC, DeviceInfos::model, networkConfig, nodemap, NetworkConfig::packetDelayNs, CameraConfig::pixelFormat, RED, RESET, DeviceInfos::serialNumber, streamConfig, DeviceInfos::timestampFrequency, DeviceInfos::tlType, NetworkConfig::transmissionDelayNs, DeviceInfos::vendor, DeviceInfos::version, StreamConfig::videoHeight, StreamConfig::videoWidth, and CameraConfig::width.
~Camera()
Camera::~Camera ()
Definition at line 112 of file Camera.cpp.
 {
     if (device)
     {
         try
         {
             device->close();
             if (debug)
             {
                 std::cout << GREEN << "[DEBUG] Camera " << device->getID() << ": Closed successfully" << RESET << std::endl;
             }
         }
         catch (const std::exception &ex)
         {
             std::cerr << RED << "Error: Failed to close camera " << device->getID() << ": " << ex.what() << RESET << std::endl;
         }
     }
 }
References debug, device, GREEN, RED, and RESET.
Member Function Documentation
adjustFpsDynamically()
void Camera::adjustFpsDynamically (double fps, double & lastFpsAdjustment) private
Definition at line 1121 of file Camera.cpp.
 {
     double currentFps = getFps();
     double globalMaxFps = getGlobalFpsUpperBound();
     if (std::abs(meanFps - lastFpsAdjustment) > 1.0)
     {
         double newFps = lastFpsAdjustment * 0.98;
         setGlobalFpsUpperBound(newFps);
         setFps(newFps);
         lastFpsAdjustment = newFps;
         std::cout << "[DEBUG] FPS dynamically adjusted to: " << newFps << std::endl;
     }
 }
References getFps(), getGlobalFpsUpperBound(), setFps(), and setGlobalFpsUpperBound().
Referenced by updateGlobalFrame().
calculateFps()
double Camera::calculateFps (double linkSpeedBps, double packetSizeB)
Definition at line 529 of file Camera.cpp.
 {
     double frameTransmissionCycle = calculateFrameTransmissionCycle(deviceLinkSpeedBps, packetSizeB);
     return std::floor(1 / frameTransmissionCycle);
 }
References calculateFrameTransmissionCycle(), and packetSizeB.
calculateFrameTransmissionCycle()
double Camera::calculateFrameTransmissionCycle (double linkSpeedBps, double packetSizeB) private
Definition at line 1095 of file Camera.cpp.
 {
     double RawFrameSizeBytes = calculateRawFrameSizeB(cameraConfig.width, cameraConfig.height, cameraConfig.pixelFormat);
     double numPacketPerFrameB = RawFrameSizeBytes / packetSizeB;
     double frameTransmissionCycle = RawFrameSizeBytes / deviceLinkSpeedBps;
     return frameTransmissionCycle + numPacketPerFrameB * networkConfig.packetDelayNs * 1e-9; // ToDo check if correct, should i add transmission delay
 }
References calculateRawFrameSizeB(), cameraConfig, CameraConfig::height, networkConfig, NetworkConfig::packetDelayNs, packetSizeB, CameraConfig::pixelFormat, and CameraConfig::width.
Referenced by calculateFps().
calculatePacketDelayNs()
double Camera::calculatePacketDelayNs (double packetSizeB, double linkSpeedBps, double bufferPercent, double numCams) private
Definition at line 1089 of file Camera.cpp.
 {
     double buffer = (bufferPercent / 100.0) * (packetSizeB * (1e9 / deviceLinkSpeedBps));
     return (((packetSizeB * (1e9 / deviceLinkSpeedBps)) + buffer) * (numCams - 1));
 }
References bufferPercent, and packetSizeB.
Referenced by setBandwidthDelays().
calculateRawFrameSizeB()
double Camera::calculateRawFrameSizeB (int width, int height, PfncFormat_ pixelFormat) private
Definition at line 1103 of file Camera.cpp.
 {
     int bitsPerPixel = getBitsPerPixel(pixelFormat);
     int totalPixels = width * height;
     int totalBits = totalPixels * bitsPerPixel;
     return static_cast<double>(totalBits) / 8.0; // Convert bits to bytes
 }
References getBitsPerPixel().
Referenced by calculateFrameTransmissionCycle().
cleanupStream()
void Camera::cleanupStream (std::shared_ptr< rcg::Stream > & stream) private
Definition at line 837 of file Camera.cpp.
 {
     try
     {
         stream->stopStreaming();
         stream->close();
     }
     catch (const std::exception &ex)
     {
         std::cerr << RED << "Exception during stream cleanup for camera " << device->getID()
                   << ": " << ex.what() << RESET << std::endl;
     }
 }
References device, RED, and RESET.
Referenced by startStreaming().
decimalToIP()
std::string Camera::decimalToIP (uint32_t decimalIP) private
Definition at line 1155 of file Camera.cpp.
 {
     struct in_addr ip_addr;
     ip_addr.s_addr = htonl(3232236391);
     return std::string(inet_ntoa(ip_addr));
 }
Referenced by getCurrentIP(), and hexToIP().
decimalToMAC()
std::string Camera::decimalToMAC (uint64_t decimalMAC) private
Definition at line 1168 of file Camera.cpp.
 {
     std::ostringstream macStream;
     for (int i = 5; i >= 0; --i)
     {
         macStream << std::hex << std::setw(2) << std::setfill('0') << ((decimalMAC >> (i * 8)) & 0xFF);
         if (i > 0)
             macStream << ":";
     }
     return macStream.str();
 }
Referenced by getMAC(), and hexToMAC().
getBitsPerPixel()
int Camera::getBitsPerPixel (PfncFormat_ pixelFormat) private
Definition at line 1219 of file Camera.cpp.
 {
     switch (pixelFormat)
     {
     // 24-bit formats (3 channels  8 bits)
     case BGR8:
     case RGB8:
         return 24;
     // 32-bit formats (4 channels  8 bits)
     case RGBa8:
     case BGRa8:
         return 32;
     // 8-bit formats (1 channel  8 bits)
     case Mono8:
     case BayerRG8:
     case BayerBG8:
     case BayerGB8:
     case BayerGR8:
         return 8;
     // 16-bit formats (1 channel  16 bits)
     case Mono16:
         return 16;
     // YUV/YCbCr formats (typically 16 bits per pixel for YUY2/UYVY)
     case YCbCr422_8:
     case YUV422_8:
         return 16; // 4:2:2 subsampling means 16 bits per pixel
     default:
         std::cerr << RED << "Unknown pixel format: " << pixelFormat << RESET << std::endl;
         return 0;
     }
 }
References RED, and RESET.
Referenced by calculateRawFrameSizeB().
getCurrentIP()
std::string Camera::getCurrentIP ()
Definition at line 582 of file Camera.cpp.
 {
     try
     {
         std::string currentIP = rcg::getString(nodemap, "GevCurrentIPAddress");
         if (!isDottedIP(currentIP))
         {
             try
             {
                 if (currentIP.find_first_not_of("0123456789") == std::string::npos)
                 {
                     currentIP = decimalToIP(std::stoul(currentIP));
                 }
                 else
                 {
                     currentIP = hexToIP(currentIP);
                 }
             }
             catch (const std::invalid_argument &e)
             {
                 std::cerr << "Invalid IP address format: " << currentIP << std::endl;
                 currentIP = "";
             }
         }
         return currentIP;
     }
     catch (const std::exception &ex)
     {
         std::cerr << "Exception: " << ex.what() << std::endl;
         return "";
     }
 }
References decimalToIP(), hexToIP(), isDottedIP(), and nodemap.
Referenced by Camera().
getExposureTime()
double Camera::getExposureTime ()
Definition at line 539 of file Camera.cpp.
 {
     double exposure = 0.0;
     try
     {
         if (deviceInfos.deprecatedFW)
         {
             exposure = rcg::getFloat(nodemap, "ExposureTimeAbs");
         }
         else
         {
             exposure = rcg::getFloat(nodemap, "ExposureTime");
         }
     }
     catch (const std::exception &e)
     {
         std::cerr << "Failed to set exposure time for camera " << deviceInfos.id << ": " << e.what() << std::endl;
     }
     return exposure;
 }
References DeviceInfos::deprecatedFW, deviceInfos, DeviceInfos::id, and nodemap.
getFps()
double Camera::getFps ()
Definition at line 561 of file Camera.cpp.
 {
     double fps = 0.0;
     try
     {
         if (!deviceInfos.deprecatedFW)
         {
             fps = rcg::getFloat(nodemap, "AcquisitionFrameRate");
         }
         else
         {
             fps = rcg::getFloat(nodemap, "AcquisitionFrameRateAbs");
         }
     }
     catch (const std::exception &e)
     {
         std::cerr << "Failed to get frame rate for camera " << deviceInfos.id << ": " << e.what() << std::endl;
     }
     return fps;
 }
References DeviceInfos::deprecatedFW, deviceInfos, DeviceInfos::id, and nodemap.
Referenced by adjustFpsDynamically().
getLastSavedFps()
double Camera::getLastSavedFps () const inline
Definition at line 126 of file Camera.hpp.
 { return lastSavedFps; }
References lastSavedFps.
Referenced by isFpsStableForSaving(), and startStreaming().
getMAC()
std::string Camera::getMAC ()
Definition at line 614 of file Camera.cpp.
 {
     std::regex macPattern(R"(^([0-9A-Fa-f]{2}:){5}([0-9A-Fa-f]{2})$)");
     try
     {
         std::string MAC = rcg::getString(nodemap, "GevMACAddress");
         if (!std::regex_match(MAC, macPattern))
         {
             try
             {
                 if (MAC.find_first_not_of("0123456789") == std::string::npos)
                 {
                     uint64_t decimalMAC = std::stoull(MAC);
                     MAC = decimalToMAC(decimalMAC);
                 }
                 else
                 {
                     MAC = hexToMAC(MAC);
                 }
             }
             catch (const std::invalid_argument &e)
             {
                 std::cerr << "Invalid MAC address format: " << MAC << std::endl;
                 MAC = "";
             }
         }
         return MAC;
     }
     catch (const std::exception &ex)
     {
         std::cerr << "Exception: " << ex.what() << std::endl;
         return "";
     }
 }
References decimalToMAC(), hexToMAC(), and nodemap.
Referenced by Camera().
getPixelFormat()
PfncFormat_ Camera::getPixelFormat (const std::string & format) private
Definition at line 1186 of file Camera.cpp.
 {
     // Map common format strings to enum values
     if (format == "BGR8")
         return BGR8;
     if (format == "RGB8")
         return RGB8;
     if (format == "RGBa8")
         return RGBa8;
     if (format == "BGRa8")
         return BGRa8;
     if (format == "Mono8")
         return Mono8;
     if (format == "Mono16")
         return Mono16;
     if (format == "BayerRG8")
         return BayerRG8;
     if (format == "BayerBG8")
         return BayerBG8;
     if (format == "BayerGB8")
         return BayerGB8;
     if (format == "BayerGR8")
         return BayerGR8;
     if (format == "YCbCr422_8")
         return YCbCr422_8;
     if (format == "YUV422_8")
         return YUV422_8;
     // Default case if no match found
     std::cerr << RED << "Unknown pixel format string: " << format << RESET << std::endl;
     return Mono8; // Return a default format as fallback
 }
References RED, and RESET.
Referenced by Camera().
getPtpConfig()
void Camera::getPtpConfig ()
Definition at line 649 of file Camera.cpp.
 {
     try
     {
         if (!deviceInfos.deprecatedFW)
         {
             rcg::callCommand(nodemap, "PtpDataSetLatch");
             ptpConfig.enabled = rcg::getBoolean(nodemap, "PtpEnable");
             ptpConfig.status = rcg::getString(nodemap, "PtpStatus");
             ptpConfig.offsetFromMaster = rcg::getInteger(nodemap, "PtpOffsetFromMaster");
         }
         else
         {
             rcg::callCommand(nodemap, "GevIEEE1588DataSetLatch");
             ptpConfig.enabled = rcg::getBoolean(nodemap, "GevIEEE1588");
             ptpConfig.status = rcg::getString(nodemap, "GevIEEE1588Status");
             try
             {
                 // Basler Cameras
                 ptpConfig.offsetFromMaster = rcg::getInteger(nodemap, "GevIEEE1588OffsetFromMaster");
             }
             catch (const std::exception &ex)
             {
                 ptpConfig.offsetFromMaster = 0; // Unavailable
             }
         }
     }
     catch (const std::exception &ex)
     {
         std::cerr << RED << "Error: Failed to get PTP parameters: " << ex.what() << RESET << std::endl;
     }
 }
References DeviceInfos::deprecatedFW, deviceInfos, PtpConfig::enabled, nodemap, PtpConfig::offsetFromMaster, ptpConfig, RED, RESET, and PtpConfig::status.
getTimestamps()
void Camera::getTimestamps ()
Definition at line 682 of file Camera.cpp.
 {
     try
     {
         if (!deviceInfos.deprecatedFW)
         {
             rcg::callCommand(this->nodemap, "TimestampLatch");
             ptpConfig.timestamp_ns = rcg::getInteger(this->nodemap, "TimestampLatchValue");
         }
         else
         {
             rcg::callCommand(this->nodemap, "GevTimestampControlLatch");
             ptpConfig.timestamp_ns = rcg::getInteger(this->nodemap, "GevTimestampValue");
         }
         ptpConfig.timestamp_s = static_cast<double>(ptpConfig.timestamp_ns) / 1e9;
     }
     catch (const std::exception &ex)
     {
         std::cerr << RED << "Error: Failed to get timestamp: " << ex.what() << RESET << std::endl;
     }
 }
References DeviceInfos::deprecatedFW, deviceInfos, nodemap, ptpConfig, RED, RESET, PtpConfig::timestamp_ns, and PtpConfig::timestamp_s.
Referenced by updateGlobalFrame().
hexToIP()
std::string Camera::hexToIP (const std::string & hexIP) private
Definition at line 1162 of file Camera.cpp.
 {
     uint32_t decimalIP = std::stoul(hexIP, nullptr, 16);
     return decimalToIP(decimalIP);
 }
References decimalToIP().
Referenced by getCurrentIP().
hexToMAC()
std::string Camera::hexToMAC (const std::string & hexMAC) private
Definition at line 1180 of file Camera.cpp.
 {
     uint64_t decimalMAC = std::stoull(hexMAC, nullptr, 16);
     return decimalToMAC(decimalMAC);
 }
References decimalToMAC().
Referenced by getMAC().
initializeStream()
std::shared_ptr< rcg::Stream > Camera::initializeStream () private
Definition at line 851 of file Camera.cpp.
 {
     auto streamList = device->getStreams();
     if (streamList.empty())
     {
         std::cerr << RED << "No stream available for camera " << device->getID() << RESET << std::endl;
         return nullptr;
     }
     auto stream = streamList[0]; // Select the first available stream
     try
     {
         stream->open();
         stream->attachBuffers(true);
         stream->startStreaming();
         if (debug)
             std::cout << GREEN << "[DEBUG] Stream started for camera " << device->getID() << RESET << std::endl;
         return stream;
     }
     catch (const std::exception &ex)
     {
         std::cerr << RED << "Failed to start stream for camera " << device->getID() << ": " << ex.what() << RESET << std::endl;
         return nullptr;
     }
 }
References debug, device, GREEN, RED, and RESET.
Referenced by startStreaming().
initializeVideoWriter()
void Camera::initializeVideoWriter (int width, int height) private
Definition at line 878 of file Camera.cpp.
 {
     streamConfig.videoWidth = width + (width % 2);   // Ensure even width
     streamConfig.videoHeight = height + (height % 2);
     // Directory structure
     const std::string outputDir = "./output/recordings";
     const std::string sessionTimestamp = getSessionTimestamp(); // e.g., 20250330_113200
     const std::string sessionDir = outputDir + "/" + sessionTimestamp;
     const std::string camID = deviceInfos.serialNumber;
     const std::string camDir = sessionDir + "/" + camID + "_" + sessionTimestamp;
     try
     {
         std::filesystem::create_directories(camDir);
     }
     catch (const std::exception &ex)
     {
         std::cerr << RED << "[ERROR] Failed to create output directories: " << ex.what() << RESET << std::endl;
         return;
     }
     // Timestamp for video filename
     auto now = std::chrono::system_clock::now();
     std::time_t now_time_t = std::chrono::system_clock::to_time_t(now);
     std::tm tm = *std::localtime(&now_time_t);
     std::ostringstream timestampStream;
     timestampStream << std::put_time(&tm, "%Y%m%d_%H%M%S");
     // Sanitize device ID for filenames
     std::string sanitizedId = deviceInfos.id;
     std::replace(sanitizedId.begin(), sanitizedId.end(), '(', '_');
     std::replace(sanitizedId.begin(), sanitizedId.end(), ')', '_');
     std::replace(sanitizedId.begin(), sanitizedId.end(), ' ', '_');
     // Try different codecs
     std::vector<std::pair<std::string, int>> codecOptions = {
         {".mp4", cv::VideoWriter::fourcc('a', 'v', 'c', '1')}, // H.264
         {".avi", cv::VideoWriter::fourcc('X', 'V', 'I', 'D')}, // XVID
         {".avi", cv::VideoWriter::fourcc('M', 'J', 'P', 'G')}, // MJPG
         {".avi", cv::VideoWriter::fourcc('D', 'I', 'V', 'X')}  // DIVX
     };
     double fps = getGlobalFpsUpperBound();
     std::string outputPath;
     bool videoOpened = false;
     for (const auto &codecOption : codecOptions)
     {
         std::string extension = codecOption.first;
         int codec = codecOption.second;
         std::string filename = "camera_" + sanitizedId + "_" + timestampStream.str() + extension;
         outputPath = camDir + "/" + filename;
         if (debug)
         {
             std::cout << GREEN << "[DEBUG] Camera " << device->getID() << ": Trying codec: "
                       << static_cast<char>(codec & 0xFF)
                       << static_cast<char>((codec >> 8) & 0xFF)
                       << static_cast<char>((codec >> 16) & 0xFF)
                       << static_cast<char>((codec >> 24) & 0xFF)
                       << " for file: " << outputPath << RESET << std::endl;
         }
         videoWriter.open(outputPath, codec, fps, cv::Size(streamConfig.videoWidth, streamConfig.videoHeight), true);
         if (videoWriter.isOpened())
         {
             videoOpened = true;
             break;
         }
         else
         {
             std::cerr << RED << "[ERROR] Failed to open video with codec: "
                       << static_cast<char>(codec & 0xFF)
                       << static_cast<char>((codec >> 8) & 0xFF)
                       << static_cast<char>((codec >> 16) & 0xFF)
                       << static_cast<char>((codec >> 24) & 0xFF)
                       << RESET << std::endl;
         }
     }
     if (!videoOpened)
     {
         std::cerr << RED << "[ERROR] All codecs failed. Video recording disabled." << RESET << std::endl;
         return;
     }
     if (debug)
     {
         std::cout << GREEN << "[DEBUG] Camera " << device->getID()
                   << ": Video recording started at: " << outputPath << RESET << std::endl;
     }
 }
References debug, device, deviceInfos, getGlobalFpsUpperBound(), getSessionTimestamp(), GREEN, DeviceInfos::id, RED, RESET, DeviceInfos::serialNumber, streamConfig, StreamConfig::videoHeight, StreamConfig::videoWidth, and videoWriter.
Referenced by startStreaming().
isDottedIP()
bool Camera::isDottedIP (const std::string & ip) private
Definition at line 1137 of file Camera.cpp.
 {
     std::regex ipPattern(R"(^(\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})$)");
     std::smatch match;
     if (std::regex_match(ip, match, ipPattern))
     {
         for (int i = 1; i <= 4; ++i)
         {
             int octet = std::stoi(match[i].str());
             if (octet < 0 || octet > 255)
                 return false;
         }
         return true;
     }
     return false;
 }
Referenced by getCurrentIP().
isFpsStableForSaving()
bool Camera::isFpsStableForSaving (double tolerance = 1.0) const private
Definition at line 1116 of file Camera.cpp.
 {
     return std::abs(getLastSavedFps() - getLastSavedFps()) <= tolerance; // ToDo
 }
References getLastSavedFps().
Referenced by startStreaming().
issueScheduledActionCommand()
void Camera::issueScheduledActionCommand (uint32_t actionDeviceKey, uint32_t groupKey, uint32_t groupMask, int64_t delayS, const std::string & targetIP = "255.255.255.255")
Definition at line 504 of file Camera.cpp.
 {
     try
     {
         rcg::setString(nodemap, "ActionCommandTargetIP", targetIP.c_str());
         rcg::setInteger(nodemap, "ActionCommandExecuteTime", scheduledDelayS);
         rcg::callCommand(nodemap, "ActionCommandFireCommand");
         if (debug)
         {
             std::cout << GREEN << "issueScheduledActionCommand success" << RESET << std::endl;
         }
     }
     catch (const std::exception &e)
     {
         std::cerr << RED << "Error: Failed to issue scheduled action command: " << e.what() << RESET << std::endl;
     }
 }
References debug, GREEN, nodemap, RED, and RESET.
logBandwidthDelaysToCSV()
void Camera::logBandwidthDelaysToCSV (const std::string & camID, int64_t packetDelayNs, int64_t transmissionDelayNs) private
Definition at line 1256 of file Camera.cpp.
 {
     const std::string outputDir = "./output";
     const std::string bandwidthDir = outputDir + "/bandwidth";
     const std::string sessionStartTimeStr = getSessionTimestamp();
     const std::string csvPath = bandwidthDir + "/bandwidth_delays_" + sessionStartTimeStr + ".csv";
     std::filesystem::create_directories(bandwidthDir);
     bool writeHeader = !std::filesystem::exists(csvPath);
     std::ofstream csvFile(csvPath, std::ios::app);
     if (csvFile.is_open())
     {
         if (writeHeader)
             csvFile << "CameraID,PacketDelayNs,TransmissionDelayNs\n";
         csvFile << camID << "," << packetDelayNs << "," << transmissionDelayNs << "\n";
         csvFile.close();
     }
     else
     {
         std::cerr << RED << "[ERROR] Could not open " << csvPath << " for writing." << RESET << std::endl;
     }
 }
References getSessionTimestamp(), RED, and RESET.
Referenced by setBandwidthDelays().
processFrame()
void Camera::processFrame (const rcg::Buffer * buffer, cv::Mat & outputFrame) private
Definition at line 814 of file Camera.cpp.
 {
     if (buffer && !buffer->getIsIncomplete() && buffer->getImagePresent(0))
     {
         rcg::Image image(buffer, 0);
         cv::Mat rawFrame(image.getHeight(), image.getWidth(), CV_8UC1, (void *)image.getPixels());
         uint64_t format = image.getPixelFormat();
         Camera::processRawFrame(rawFrame, outputFrame, format);
         // Resize the frame to a fixed resolution
         if (!outputFrame.empty())
         {
             cv::resize(outputFrame, outputFrame, cv::Size(640, 480));
         }
     }
     else
     {
         std::cerr << YELLOW << "Camera " << device->getID() << ": Invalid image grabbed." << RESET << std::endl;
         return;
     }
 }
References device, processRawFrame(), RESET, and YELLOW.
Referenced by startStreaming().
processRawFrame()
void Camera::processRawFrame (const cv::Mat & rawFrame, cv::Mat & outputFrame, uint64_t pixelFormat) private
Process a raw frame based on the pixel format.
Definition at line 711 of file Camera.cpp.
 {
     try
     {
         switch (pixelFormat)
         {
         case BGR8:
             outputFrame = rawFrame.clone();
             break;
         case RGB8:
             cv::cvtColor(rawFrame, outputFrame, cv::COLOR_RGB2BGR);
             break;
         case RGBa8:
             cv::cvtColor(rawFrame, outputFrame, cv::COLOR_RGBA2BGR);
             break;
         case BGRa8:
             cv::cvtColor(rawFrame, outputFrame, cv::COLOR_BGRA2BGR);
             break;
         case Mono8:
             outputFrame = rawFrame.clone();
             break;
         case Mono16:
             rawFrame.convertTo(outputFrame, CV_8UC1, 1.0 / 256.0);
             break;
         case BayerRG8:
             cv::cvtColor(rawFrame, outputFrame, cv::COLOR_BayerBG2BGR); // ToDo
             break;
         case BayerBG8:
             cv::cvtColor(rawFrame, outputFrame, cv::COLOR_BayerBG2BGR);
             break;
         case BayerGB8:
             cv::cvtColor(rawFrame, outputFrame, cv::COLOR_BayerGB2BGR);
             break;
         case BayerGR8:
             cv::cvtColor(rawFrame, outputFrame, cv::COLOR_BayerGR2BGR);
             break;
         case YCbCr422_8:
             cv::cvtColor(rawFrame, outputFrame, cv::COLOR_YUV2BGR_YUY2);
             break;
         case YUV422_8:
             cv::cvtColor(rawFrame, outputFrame, cv::COLOR_YUV2BGR_UYVY);
             break;
         default:
             std::cerr << RED << "Unsupported pixel format: " << pixelFormat << RESET << std::endl;
             outputFrame = rawFrame.clone();
             break;
         }
     }
     catch (const std::exception &ex)
     {
         std::cerr << RED << "Exception in processRawFrame: " << ex.what() << RESET << std::endl;
     }
 }
References RED, and RESET.
Referenced by processFrame().
saveFrameToPng()
void Camera::saveFrameToPng (const cv::Mat & frame) private
Definition at line 1027 of file Camera.cpp.
 {
     if (frame.empty())
     {
         std::cerr << RED << "[ERROR] Cannot save empty frame to PNG." << RESET << std::endl;
         return;
     }
     // Output path construction
     const std::string outputDir = "./output/recordings";
     const std::string sessionTimestamp = getSessionTimestamp(); // e.g. "20250330_113200"
     const std::string sessionDir = outputDir + "/" + sessionTimestamp;
     const std::string camID = deviceInfos.serialNumber;
     const std::string camDir = sessionDir + "/" + camID + "_" + sessionTimestamp;
     try
     {
         std::filesystem::create_directories(camDir);
     }
     catch (const std::exception &ex)
     {
         std::cerr << RED << "[ERROR] Failed to create output directories: " << ex.what() << RESET << std::endl;
         return;
     }
     // Convert grayscale to BGR if needed
     cv::Mat pngFrame;
     if (frame.channels() == 1)
     {
         cv::cvtColor(frame, pngFrame, cv::COLOR_GRAY2BGR);
     }
     else
     {
         pngFrame = frame;
     }
     // Save PNG with timestamp
     auto now = std::chrono::high_resolution_clock::now();
     auto nowNs = std::chrono::duration_cast<std::chrono::nanoseconds>(now.time_since_epoch()).count();
     const std::string filename = camDir + "/frame_" + std::to_string(nowNs) + ".png";
     try
     {
         if (!cv::imwrite(filename, pngFrame))
         {
             std::cerr << RED << "[ERROR] Failed to write PNG: " << filename << RESET << std::endl;
         }
         else if (debug)
         {
             std::cout << GREEN << "[INFO] Saved PNG: " << filename << RESET << std::endl;
         }
     }
     catch (const std::exception &ex)
     {
         std::cerr << RED << "[ERROR] Exception writing PNG: " << ex.what() << RESET << std::endl;
     }
 }
References debug, deviceInfos, getSessionTimestamp(), GREEN, RED, RESET, and DeviceInfos::serialNumber.
Referenced by startStreaming().
saveFrameToVideo()
void Camera::saveFrameToVideo (cv::VideoWriter & videoWriter, const cv::Mat & frame) private
Definition at line 974 of file Camera.cpp.
 {
     if (!videoWriter.isOpened())
     {
         std::cerr << RED << "[ERROR] Video writer is not opened." << RESET << std::endl;
         return;
     }
     if (frame.empty())
     {
         std::cerr << RED << "[ERROR] Cannot save empty frame to video." << RESET << std::endl;
         return;
     }
     cv::Mat colorFrame;
     if (frame.channels() == 1)
     {
         cv::cvtColor(frame, colorFrame, cv::COLOR_GRAY2BGR);
     }
     else
     {
         colorFrame = frame;
     }
     cv::Mat resizedFrame;
     if (colorFrame.cols != streamConfig.videoWidth || colorFrame.rows != streamConfig.videoHeight)
     {
         try
         {
             cv::resize(colorFrame, resizedFrame, cv::Size(streamConfig.videoWidth, streamConfig.videoHeight));
         }
         catch (const std::exception &ex)
         {
             std::cerr << RED << "[ERROR] Failed to resize frame: " << ex.what() << RESET << std::endl;
             return;
         }
     }
     else
     {
         resizedFrame = colorFrame;
     }
     try
     {
         videoWriter.write(resizedFrame);
         frameCounter++;
     }
     catch (const std::exception &ex)
     {
         std::cerr << RED << "[ERROR] Exception writing frame: " << ex.what() << RESET << std::endl;
     }
 }
References frameCounter, RED, RESET, streamConfig, StreamConfig::videoHeight, StreamConfig::videoWidth, and videoWriter.
Referenced by startStreaming().
setBandwidthDelays()
void Camera::setBandwidthDelays (const std::shared_ptr< Camera > & camera, double camIndex, double numCams, double packetSizeB, double linkSpeedBps, double bufferPercent)
Definition at line 354 of file Camera.cpp.
 {
     try
     {
         networkConfig.packetDelayNs = calculatePacketDelayNs(packetSizeB, deviceLinkSpeedBps, bufferPercent, numCams);
         networkConfig.transmissionDelayNs = networkConfig.packetDelayNs * (numCams - 1 - camIndex);
         networkConfig.packetDelayNs = static_cast<int64_t>((networkConfig.packetDelayNs + 7) / 8) * 8; // Ensure multiple of 8
         rcg::setInteger(camera->nodemap, "GevSCPD", networkConfig.packetDelayNs);                      // in counter units, 1ns resolution if ptp is enabled
         networkConfig.transmissionDelayNs = static_cast<int64_t>((networkConfig.transmissionDelayNs + 7) / 8) * 8;
         rcg::setInteger(camera->nodemap, "GevSCFTD", networkConfig.transmissionDelayNs); // in counter units, 1ns resolution if ptp is enabled
         if (debug)
             std::cout << YELLOW << "[DEBUG] Camera " << device->getID() << " numCams: " << numCams << " | CamIndex: " << camIndex
                       << " | packetSizeB: " << packetSizeB << " | deviceLinkSpeedBps: " << deviceLinkSpeedBps
                       << " | bufferPercent: " << bufferPercent << std::endl;
         std::cout << YELLOW << "[DEBUG] Camera " << device->getID() << ": Calculated packet delay: " << networkConfig.packetDelayNs << " ns, Calculated transmission delay: " << networkConfig.transmissionDelayNs << " ns" << RESET << std::endl;
         std::cout << GREEN << "[DEBUG] Camera " << device->getID() << ": GevSCPD set to: " << rcg::getInteger(nodemap, "GevSCPD") << " ns, GevSCFTD set to: " << rcg::getInteger(nodemap, "GevSCFTD") << " ns" << RESET << std::endl;
         logBandwidthDelaysToCSV(device->getID(), networkConfig.packetDelayNs, networkConfig.transmissionDelayNs);
     }
     catch (const std::exception &ex)
     {
         std::cerr << RED << "Failed to set bandwidth for camera " << device->getID() << ": " << ex.what() << RESET << std::endl;
     }
 }
References bufferPercent, calculatePacketDelayNs(), debug, device, GREEN, logBandwidthDelaysToCSV(), networkConfig, nodemap, NetworkConfig::packetDelayNs, packetSizeB, RED, RESET, NetworkConfig::transmissionDelayNs, and YELLOW.
setExposureTime()
void Camera::setExposureTime (double exposureTime)
Definition at line 457 of file Camera.cpp.
{
 try
 {
     rcg::setEnum(nodemap, "ExposureMode", "Timed");
     rcg::setEnum(nodemap, "ExposureAuto", "Off");
     if (deviceInfos.deprecatedFW)
     {
         rcg::setFloat(nodemap, "ExposureTimeAbs", exposureTime);
     }
     else
     {
         rcg::setFloat(nodemap, "ExposureTime", exposureTime);
     }
     if (debug)
         if (deviceInfos.deprecatedFW)
         {
             std::cout << GREEN << "[DEBUG] Camera " << deviceInfos.id << " ExposureTime set to:" << rcg::getFloat(nodemap, "ExposureTimeAbs") << RESET << std::endl; // ExposureTime // ToDo for all or only deprecated ?
         }
         else
         {
             std::cout << GREEN << "[DEBUG] Camera " << deviceInfos.id << " ExposureTime set to:" << rcg::getFloat(nodemap, "ExposureTime") << RESET << std::endl; // ExposureTime // ToDo for all or only deprecated ?
         }
 }
 catch (const std::exception &e)
 {
     std::cerr << "Failed to set exposure time for camera " << deviceInfos.id << ": " << e.what() << std::endl;
 }
 }
References debug, DeviceInfos::deprecatedFW, deviceInfos, GREEN, DeviceInfos::id, nodemap, and RESET.
setFps()
void Camera::setFps (double fpsUpperBound)
Definition at line 380 of file Camera.cpp.
 {
     try
     {
         rcg::setBoolean(nodemap, "AcquisitionFrameRateEnable", true);
         if (!deviceInfos.deprecatedFW)
         {
             rcg::setFloat(nodemap, "AcquisitionFrameRate", fps);
             if (debug)
             {
                 std::cout << GREEN << "[DEBUG] Camera " << deviceInfos.id << " fps set to:" << rcg::getFloat(nodemap, "AcquisitionFrameRate") << RESET << std::endl;
             }
         }
         else
         {
             rcg::setFloat(nodemap, "AcquisitionFrameRateAbs", fps);
             if (debug)
                 std::cout << GREEN << "[DEBUG] Camera " << deviceInfos.id << " fps set to:" << rcg::getFloat(nodemap, "AcquisitionFrameRateAbs") << RESET << std::endl;
         }
     }
     catch (const std::exception &e)
     {
         std::cerr << "Failed to set frame rate for camera " << deviceInfos.id << ": " << e.what() << std::endl;
     }
 }
References debug, DeviceInfos::deprecatedFW, deviceInfos, GREEN, DeviceInfos::id, nodemap, and RESET.
Referenced by adjustFpsDynamically().
setFreeRunMode()
void Camera::setFreeRunMode ()
Definition at line 294 of file Camera.cpp.
 {
     try
     {
         rcg::setEnum(nodemap, "AcquisitionMode", "Continuous");
         rcg::setEnum(nodemap, "TriggerSelector", "FrameStart");
         rcg::setEnum(nodemap, "TriggerMode", "Off");
     }
     catch (const std::exception &ex)
     {
         std::cerr << RED << "Failed to configure free-run mode for camera " << deviceInfos.id << ": " << ex.what() << RESET << std::endl;
     }
 }
References deviceInfos, DeviceInfos::id, nodemap, RED, and RESET.
setGain()
void Camera::setGain (float gain)
Definition at line 406 of file Camera.cpp.
 {
     try
     {
         rcg::setFloat(nodemap, "Gain", gain);
         if (debug)
         {
             std::cout << GREEN << "[DEBUG] Camera " << deviceInfos.id << " Gain set to:" << rcg::getFloat(nodemap, "Gain") << RESET << std::endl;
         }
     }
     catch (const std::exception &e)
     {
         std::cerr << "Failed to set exposure time for camera " << deviceInfos.id << ": " << e.what() << std::endl;
     }
 }
References debug, deviceInfos, GREEN, DeviceInfos::id, nodemap, and RESET.
setHeight()
void Camera::setHeight (int height)
Definition at line 425 of file Camera.cpp.
 {
     try
     {
         rcg::setInteger(nodemap, "Height", height);
         if (debug)
         {
             std::cout << GREEN << "[DEBUG] Camera " << deviceInfos.id << " Height set to:" << rcg::getInteger(nodemap, "Height") << RESET << std::endl;
         }
     }
     catch (const std::exception &e)
     {
         std::cerr << "Failed to set height for camera " << deviceInfos.id << ": " << e.what() << std::endl;
     }
 }
References debug, deviceInfos, GREEN, DeviceInfos::id, nodemap, and RESET.
setPacketSizeB()
void Camera::setPacketSizeB (double size)
Definition at line 341 of file Camera.cpp.
 {
     try
     {
         packetSizeB = std::ceil(packetSizeB / 4.0) * 4; // Ensure packet size is a multiple of 4
         rcg::setInteger(nodemap, "GevSCPSPacketSize", packetSizeB);
     }
     catch (const std::exception &ex)
     {
         std::cerr << RED << "Error: Failed to set GevSCPSPacketSize: " << ex.what() << RESET << std::endl;
     }
 }
References nodemap, packetSizeB, RED, and RESET.
setPixelFormat()
void Camera::setPixelFormat (std::string pixelFormat)
Definition at line 487 of file Camera.cpp.
 {
     try
     {
         rcg::setEnum(nodemap, "PixelFormat", pixelFormat.c_str());
     }
     catch (const std::exception &e)
     {
         std::cerr << "Failed to set pixel format for camera " << deviceInfos.id << ": " << e.what() << std::endl;
     }
 }
References deviceInfos, DeviceInfos::id, and nodemap.
setPtpConfig()
void Camera::setPtpConfig (bool enable = true)
Definition at line 266 of file Camera.cpp.
 {
     std::string feature = deviceInfos.deprecatedFW ? "GevIEEE1588" : "PtpEnable";
     try
     {
         if (enable)
         {
             rcg::setString(nodemap, feature.c_str(), "true", enable);
             ptpConfig.enabled = rcg::getBoolean(nodemap, feature.c_str());
             networkConfig.deviceLinkSpeedBps = rcg::getInteger(nodemap, "DeviceLinkSpeed"); // Bps
             if (deviceInfos.deprecatedFW)
             {
                 networkConfig.deviceLinkSpeedBps = rcg::getInteger(nodemap, "GevLinkSpeed") * 1000000; // MBps to Bps
             }
         }
         else
         {
             rcg::setString(nodemap, feature.c_str(), "false", enable);
             ptpConfig.enabled = rcg::getBoolean(nodemap, feature.c_str());
         }
     }
     catch (const std::exception &ex)
     {
         std::cerr << RED << "Error: Failed to set PTP: " << ex.what() << RESET << std::endl;
     }
 }
References DeviceInfos::deprecatedFW, deviceInfos, NetworkConfig::deviceLinkSpeedBps, PtpConfig::enabled, networkConfig, nodemap, ptpConfig, RED, and RESET.
setScheduledActionCommand()
void Camera::setScheduledActionCommand (uint32_t actionDeviceKey, uint32_t groupKey, uint32_t groupMask)
Definition at line 309 of file Camera.cpp.
 {
     try
     {
         rcg::setInteger(nodemap, "ActionSelector", 0);
         if (this->deviceInfos.vendor == "Lucid")
         {
             rcg::setEnum(nodemap, "ActionUnconditionalMode", "On");
             rcg::setEnum(nodemap, "TransferControlMode", "Uncontrolled");
             rcg::setEnum(nodemap, "TransferOperationMode", "Continuous");
             rcg::callCommand(nodemap, "TransferStop");
         }
         rcg::setInteger(nodemap, "ActionDeviceKey", actionDeviceKey);
         rcg::setInteger(nodemap, "ActionGroupKey", groupKey);
         rcg::setInteger(nodemap, "ActionGroupMask", groupMask);
         rcg::setEnum(nodemap, "TriggerSelector", "FrameStart");
         rcg::setEnum(nodemap, "TriggerMode", "On");
         rcg::setEnum(nodemap, "TriggerSource", "Action0");
         rcg::callCommand(nodemap, "AcquisitionStart");
         if (debug)
         {
             std::cout << GREEN << "setActionCommandDeviceConfig success" << RESET << std::endl;
         }
     }
     catch (const std::exception &e)
     {
         std::cerr << RED << "Error: Failed to set scheduled action command: " << e.what() << RESET << std::endl;
     }
 }
References debug, deviceInfos, GREEN, nodemap, RED, RESET, and DeviceInfos::vendor.
setWidth()
void Camera::setWidth (int width)
Definition at line 441 of file Camera.cpp.
 {
     try
     {
         rcg::setInteger(nodemap, "Width", width);
         if (debug)
         {
             std::cout << GREEN << "[DEBUG] Camera " << deviceInfos.id << " Width set to:" << rcg::getInteger(nodemap, "Width") << RESET << std::endl;
         }
     }
     catch (const std::exception &e)
     {
         std::cerr << "Failed to set width for camera " << deviceInfos.id << ": " << e.what() << std::endl;
     }
 }
References debug, deviceInfos, GREEN, DeviceInfos::id, nodemap, and RESET.
startStreaming()
void Camera::startStreaming (std::atomic< bool > & stopStream, std::mutex & globalFrameMutex, std::vector< cv::Mat > & globalFrames, int index, bool saveStream)
Definition at line 135 of file Camera.cpp.
 {
     auto stream = initializeStream();
     if (!stream)
         return;
     if (saveStream)
     {
         initializeVideoWriter(streamConfig.videoWidth, streamConfig.videoHeight);
     }
     auto lastTime = std::chrono::steady_clock::now();
     int frameCount = 0;
     int consecutiveFailures = 0; // Count failed grabs
     while (!stopStream.load())
     {
         const rcg::Buffer *buffer = nullptr;
         try
         {
             buffer = stream->grab(5000); // Timeout in ms
             if (!buffer)
             {
                 consecutiveFailures++;
                 if (consecutiveFailures > 10)
                 {
                     std::cerr << RED << "Error: Too many failed frame grabs for camera " << device->getID()
                               << ". Stopping stream..." << RESET << std::endl;
                     break; // Exit loop if grabbing fails too often
                 }
                 std::this_thread::sleep_for(std::chrono::milliseconds(10));
                 continue;
             }
         }
         catch (const std::exception &ex)
         {
             std::cerr << RED << "Exception during grab: " << ex.what() << RESET << std::endl;
             if (stopStream.load())
                 break;
             std::this_thread::sleep_for(std::chrono::milliseconds(100));
             continue;
         }
         consecutiveFailures = 0;
         cv::Mat outputFrame;
         try
         {
             processFrame(buffer, outputFrame);
         }
         catch (const std::exception &ex)
         {
             std::cerr << RED << "Exception during frame processing: " << ex.what() << RESET << std::endl;
             continue;
         }
         if (!outputFrame.empty())
         {
             updateGlobalFrame(globalFrameMutex, globalFrames, index, outputFrame, frameCount, lastTime);
             if (saveStream && isFpsStableForSaving()) // only save if stable
             {
                 if (videoWriter.isOpened())
                 {
                     try
                     {
                         saveFrameToVideo(videoWriter, outputFrame);
                     }
                     catch (const std::exception &ex)
                     {
                         std::cerr << RED << "Exception during video writing: " << ex.what() << RESET << std::endl;
                     }
                 }
                 try
                 {
                     saveFrameToPng(outputFrame);
                 }
                 catch (const std::exception &ex)
                 {
                     std::cerr << RED << "Exception during PNG saving: " << ex.what() << RESET << std::endl;
                 }
                 lastSavedFps = getLastSavedFps();
             }
             else if (saveStream)
             {
                 std::cout << "[INFO] Skipping save  FPS unstable: "
                           << "Current mean FPS = " << getLastSavedFps()
                           << ", Last saved FPS = " << getLastSavedFps() << std::endl;
             }
         }
     }
     // Clean up
     try
     {
         cleanupStream(stream);
     }
     catch (const std::exception &ex)
     {
         std::cerr << RED << "Exception during stream cleanup: " << ex.what() << RESET << std::endl;
     }
     if (saveStream && videoWriter.isOpened())
     {
         try
         {
             videoWriter.release();
             std::cout << GREEN << "[DEBUG] Camera " << device->getID() << ": saveStream success" << RESET << std::endl;
         }
         catch (const std::exception &ex)
         {
             std::cerr << RED << "Exception during video writer release: " << ex.what() << RESET << std::endl;
         }
     }
 }
References cleanupStream(), device, getLastSavedFps(), GREEN, initializeStream(), initializeVideoWriter(), isFpsStableForSaving(), lastSavedFps, processFrame(), RED, RESET, saveFrameToPng(), saveFrameToVideo(), stopStream, streamConfig, updateGlobalFrame(), StreamConfig::videoHeight, StreamConfig::videoWidth, and videoWriter.
stopStreaming()
void Camera::stopStreaming (std::shared_ptr< rcg::Stream > stream)
updateGlobalFrame()
void Camera::updateGlobalFrame (std::mutex & globalFrameMutex, std::vector< cv::Mat > & globalFrames, int index, cv::Mat & frame, int & frameCount, std::chrono::steady_clock::time_point & lastTime) private
Definition at line 765 of file Camera.cpp.
 {
     static std::deque<double> fpsHistory;
     int maxHistorySize = ptpMaxCheck;
     frameCount++;
     auto currentTime = std::chrono::steady_clock::now();
     double elapsed = std::chrono::duration_cast<std::chrono::milliseconds>(currentTime - lastTime).count() / 1000.0;
     double fps = (elapsed > 0) ? frameCount / elapsed : 0.0;
     fpsHistory.push_back(fps);
     if (fpsHistory.size() > maxHistorySize)
         fpsHistory.pop_front();
     double sumFps = std::accumulate(fpsHistory.begin(), fpsHistory.end(), 0.0);
     double meanFps = sumFps / fpsHistory.size();
     static double lastFpsAdjustment = getGlobalFpsUpperBound();
     adjustFpsDynamically(meanFps, lastFpsAdjustment);
     if (elapsed >= 1.0)
     {
         lastTime = currentTime;
         frameCount = 0;
     }
     this->getTimestamps();
     uint64_t timestampNS = ptpConfig.timestamp_ns;
     std::ostringstream overlayText;
     overlayText << "FPS: " << std::fixed << std::setprecision(2) << meanFps;
     std::ostringstream camText;
     camText << "Cam: " << device->getID();
     int baseline = 0;
     cv::Size textSize = cv::getTextSize(overlayText.str(), cv::FONT_HERSHEY_SIMPLEX, 0.6, 2, &baseline);
     int textY = frame.rows - baseline - 5;
     cv::putText(frame, overlayText.str(), cv::Point(10, textY), cv::FONT_HERSHEY_SIMPLEX, 0.6, cv::Scalar(0, 0, 255), 2);
     cv::putText(frame, camText.str(), cv::Point(10, textY - textSize.height - 10), cv::FONT_HERSHEY_SIMPLEX, 0.6, cv::Scalar(0, 255, 255), 2);
     {
         std::lock_guard<std::mutex> lock(globalFrameMutex);
         globalFrames[index] = frame.clone();
     }
     lastSavedFps = meanFps;
 }
References adjustFpsDynamically(), device, getGlobalFpsUpperBound(), getTimestamps(), lastSavedFps, ptpConfig, ptpMaxCheck, and PtpConfig::timestamp_ns.
Referenced by startStreaming().
Member Data Documentation
cameraConfig
CameraConfig Camera::cameraConfig
Definition at line 130 of file Camera.hpp.
Referenced by calculateFrameTransmissionCycle(), and Camera().
device
std::shared_ptr<rcg::Device> Camera::device private
Definition at line 177 of file Camera.hpp.
Referenced by Camera(), cleanupStream(), initializeStream(), initializeVideoWriter(), processFrame(), setBandwidthDelays(), startStreaming(), updateGlobalFrame(), and ~Camera().
deviceInfos
DeviceInfos Camera::deviceInfos
Definition at line 129 of file Camera.hpp.
Referenced by Camera(), getExposureTime(), getFps(), getPtpConfig(), getTimestamps(), initializeVideoWriter(), saveFrameToPng(), setExposureTime(), setFps(), setFreeRunMode(), setGain(), setHeight(), setPixelFormat(), setPtpConfig(), setScheduledActionCommand(), and setWidth().
frameCounter
unsigned long Camera::frameCounter = 0 private
Definition at line 178 of file Camera.hpp.
Referenced by saveFrameToVideo().
lastSavedFps
double Camera::lastSavedFps = 0.0 private
Definition at line 179 of file Camera.hpp.
Referenced by getLastSavedFps(), startStreaming(), and updateGlobalFrame().
networkConfig
NetworkConfig Camera::networkConfig
Definition at line 132 of file Camera.hpp.
Referenced by calculateFrameTransmissionCycle(), Camera(), setBandwidthDelays(), and setPtpConfig().
nodemap
std::shared_ptr<GenApi::CNodeMapRef> Camera::nodemap
Definition at line 134 of file Camera.hpp.
Referenced by Camera(), getCurrentIP(), getExposureTime(), getFps(), getMAC(), getPtpConfig(), getTimestamps(), issueScheduledActionCommand(), setBandwidthDelays(), setExposureTime(), setFps(), setFreeRunMode(), setGain(), setHeight(), setPacketSizeB(), setPixelFormat(), setPtpConfig(), setScheduledActionCommand(), and setWidth().
ptpConfig
PtpConfig Camera::ptpConfig
Definition at line 131 of file Camera.hpp.
Referenced by getPtpConfig(), getTimestamps(), setPtpConfig(), and updateGlobalFrame().
streamConfig
StreamConfig Camera::streamConfig
Definition at line 133 of file Camera.hpp.
Referenced by Camera(), initializeVideoWriter(), saveFrameToVideo(), and startStreaming().
videoWriter
cv::VideoWriter Camera::videoWriter private
Definition at line 180 of file Camera.hpp.
Referenced by initializeVideoWriter(), saveFrameToVideo(), and startStreaming().
The documentation for this class was generated from the following files:
src/Camera.hpp
src/Camera.cpp